### ISSUE TITLE
Problems opening programs with comments

### ISSUE THREAD

**Issue by alu0100783230** [EleDiaz/Ram-Machine#1]
@EleDiaz,  It can't open this program  
                                                                                                                                   ```                                                                                                                                                                           

```
; Programa que lee los elementos la cinta de entrada hasta
; que encuentre un 0 y copia los valores leídos a la cinta
; de salida (el valor 0 no se copia)

    lee :   read 1
            load 1
            jzero fin
            write 1
            jump lee
    fin :   halt

```

Also you need to write a readme :+1: :alien:

**Comment by EleDiaz** [comment]
Solucionado, cosas que pasan.
